#!/usr/bin/env python3
"""翻译 Yale EP3 中文 SRT 为英文，输出 subtitles_en.srt（保留原时间戳）"""
import sys
from pathlib import Path
try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

SRT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第三期/audio/subtitles_zh.srt")
OUT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第三期/audio/subtitles_en.srt")

# 段号 → 英文（1-indexed，对应 subtitles_zh.srt 的每个字幕块）
EN = {
1:"Imagine being in a room with about 250 brilliant people, and all of them are basically offered free money.",
2:"Then imagine watching those exact same geniuses willingly walk away with absolutely nothing,",
3:"simply because they were terrified of each other.",
4:"Wow, that's a wild scenario.",
5:"Welcome to the deep dive. Today we're unpacking a fascinating set of transcripts from a Yale Game Theory course.",
6:"We're going to deconstruct a phenomenon that haunts everything from financial markets to tech startups, and even our daily social lives.",
7:"Exactly. We're looking at the psychology of group investment behavior, and specifically the dreaded herd effect.",
8:"Our mission today is to break down the psychological evolution of collective irrationality — why does the herd actually panic?",
9:"We'll also compare the real returns of blind risk versus coordinated rational decision making.",
10:"And most importantly, we want to look at the specific mechanism required to break a financial downward spiral once it starts.",
11:"You might think good investing is purely a math problem, right? Like balance sheets or profit margins.",
12:"But the math of a sound investment is completely irrelevant if the crowd around you suddenly loses its nerve.",
13:"Which happens all the time. So to truly understand this, we need to put you right in the middle of the action.",
14:"Let's visualize sitting in that massive lecture hall at Yale with those 250 other people.",
15:"The professor stands at the front and offers you a choice.",
16:"On the surface it's a very simple choice. You have a ten dollar bill.",
17:"You can either invest that ten dollars in a collective class project, or invest zero and keep your money in your pocket.",
18:"But the catch is a big catch lies in the threshold for success. If you choose to invest, you only see a return if a massive super majority of the room does exactly the same thing.",
19:"Basically everyone has to be on board.",
20:"Specifically, if more than ninety percent of the class invests, you get your ten dollars back, plus a five dollar net profit. Fifteen dollars total just for participating.",
21:"Sounds like a great deal.",
22:"It does. But if the participation rate falls just slightly short, say below ninety percent, you lose your entire ten dollars.",
23:"Wow, so you get absolutely nothing back. The project just fails.",
24:"Complete failure. Now if you choose not to invest from the start, you keep your original ten dollars. Zero risk, zero reward.",
58:"Meanwhile, those who made the defensive rational choice to not invest are sitting comfortably at zero. They didn't make money, but they didn't lose any either.",
89:"You start to worry that your neighbor will withdraw their savings. If they withdraw theirs and everyone else withdraws theirs, the bank's tiny reserve of cash will dry up before I can get my money out.",
25:"And the final critical rule is that no communication is allowed.",
26:"You have to make this choice completely in the dark, without coordinating with the person next to you.",
27:"On the surface this feels a lot like throwing a party on campus. The value of the event depends entirely on the participation of the group.",
28:"Right. The social profit, so to speak.",
29:"If everyone shows up, the party is amazing. But if nobody shows up, the handful who actually showed up are just standing around miserable, regretting they ever left their dorms.",
30:"That's such a perfect way to look at it.",
31:"What's fascinating here is that you've just highlighted the core tension of what game theorists call a Nash equilibrium.",
32:"Right. The Nash equilibrium.",
33:"In this specific game, there isn't just one logical outcome.",
34:"There are actually two completely valid, mathematically sound equilibria, and it depends entirely on human belief.",
35:"Okay, so a Nash equilibrium — if we strip away all the dense academic jargon — is simply a state of no regrets.",
36:"It's a great way to put it.",
37:"It means after the game is played, you look at your own choice and realize you did the best you possibly could have, given the actions of the rest of the group.",
38:"So mapping that onto this classroom game, you can see the obvious first equilibrium — the good one.",
39:"We all invest, we hit the ninety percent threshold, and we all make a five dollar profit. We wake up the next morning and have zero regrets.",
40:"Economists call that outcome Pareto dominant. Pareto dominance simply means a scenario where everyone is strictly better off and nobody is harmed.",
41:"The universally preferred outcome.",
42:"The problem is the existence of the second equilibrium, which is equally stable.",
43:"This is the bad equilibrium where nobody invests. We all just sit there staring at our ten dollars, too scared to make a move.",
44:"And I guess I wouldn't regret that either.",
45:"You wouldn't.",
46:"Because if I had been the only one brave enough to invest, I would have missed the ninety percent threshold and lost my ten bucks.",
47:"So staying at zero was mathematically the smartest defensive move.",
48:"Both the all-invest and the none-invest outcomes are incredibly stable. What dictates which reality you end up in is entirely based on self-fulfilling beliefs.",
49:"It's all about what you think the herd is going to do.",
50:"If you believe the group will invest, you invest, and the group succeeds. If you believe the group will hold back, you hold back, and the group fails.",
51:"This brings us directly to the psychological evolution of the herd effect. Because the professor actually runs this experiment with those 250 breathing, unpredictable humans.",
52:"And real human behavior is always messier than the theory.",
53:"In round one, everyone secretly writes down their choice. And the result reveals a deep divide in how people approach uncoordinated risk.",
54:"The room splits.",
55:"About half the class decides to be optimistic and invest their ten dollars. The other half decides to play it safe and invest nothing.",
56:"And hitting only fifty percent participation means they completely missed that crucial ninety percent threshold. The project fails.",
57:"The professor collects the hypothetical money. The investors are wiped out.",
59:"Let's compare the real returns of those two strategies. This is where the psychological evolution mechanism really kicks into gear.",
60:"The initial blind investors — the ones who took a risk hoping for the best — lost one hundred percent of their capital.",
61:"A total wipeout.",
62:"Meanwhile, the people who made the defensive rational choice to not invest are sitting comfortably at zero. They didn't make money, but they didn't lose any either.",
63:"So the defensive strategy fundamentally outperformed the blind risk strategy in round one.",
64:"And they don't just play this game once. They reset and play it again.",
65:"So what does this mean for the mindset of the room going into round two? The optimistic investors just learned a really harsh lesson.",
66:"They absolutely did. They learned that the room cannot be trusted to coordinate spontaneously. Their confidence in the collective has been totally shattered.",
67:"In round two, the people who got burned adjust their strategy. A significant portion of those initial investors decide to cut their losses and switch to the defensive strategy.",
68:"They hold onto their money.",
69:"And participation drops well below fifty percent. They missed the threshold again, and more people lose their capital.",
70:"By round three, when the professor asks who is investing, hardly anyone raises their hand.",
71:"The entire class plummets straight into that bad equilibrium. It's a textbook bear market mentality.",
72:"And the crucial insight here is that this collective irrationality isn't because people are unintelligent. It is actually born from intense individual rationality.",
73:"Wait, really? Rationality causes the panic?",
74:"Yes. Once you observe the group failing to coordinate, it becomes perfectly logical for you to stop investing.",
75:"You are protecting yourself from a systemic failure.",
76:"So the herd effect we see in financial markets isn't always a mindless animalistic panic. It is often a highly rational fear of uncoordinated action.",
77:"Exactly. When a market turns bearish, when the herd starts running for the exits, they are correctly reading the room.",
78:"They see that confidence has evaporated.",
79:"Everyone adjusts their beliefs downward at the exact same time, which makes the failure completely self-fulfilling.",
80:"The downward spiral of perfectly logical individual decisions that results in a terrible collective outcome.",
81:"It's just wild to think about. Connecting this to the bigger picture, this classroom game is really a perfect microcosm for massive real-world societal problems.",
82:"It really is. What we're looking at is a classic coordination game, which operates on an entirely different psychological axis than the more famous prisoner's dilemma.",
83:"Right. We hear about the prisoner's dilemma constantly. It's always two criminals in separate interrogation rooms being pressured to rat each other out.",
84:"That's the classic setup.",
85:"And in that scenario, you are fundamentally incentivized to betray the other person.",
86:"Even if you both agree in advance to stay silent, betraying your partner gets you less jail time.",
87:"Your dominant mathematical strategy in that game is always betrayal.",
88:"Right.",
90:"But in our investment coordination game, the exact opposite is true. Nobody wants to betray anyone.",
91:"If everyone else is investing, you desperately want to invest too. You want to coordinate to get the mutual profit.",
92:"The social failure doesn't happen because people are malicious or greedy. It happens purely because of a lack of structural coordination.",
93:"People just fail to sync up their actions, and the system collapses under the weight of mutual hesitation.",
94:"This leads us to the most potent real-world example of this mechanism: a bank run.",
95:"The sources bring up the example of Northern Rock, a bank in the UK that experienced a devastating run by its depositors.",
96:"A bank really is the ultimate real-world coordination game. That's largely because of how fractional reserve banking works, right?",
97:"Yes. When you deposit your money, the bank doesn't just lock it away. They lend the vast majority out to generate interest, keeping only a small fraction of liquid cash on hand.",
98:"So if everyone leaves their money in the bank and only makes normal day-to-day withdrawals, that's the good equilibrium.",
99:"The bank thrives, borrowers get loans, and depositors earn interest.",
100:"But that entire structure relies on the belief that everyone else will leave their money alone.",
101:"Right. If a rumor starts — like a news report suggesting the bank made bad investments — that belief fractures.",
102:"You realize the bank literally does not have enough cash to pay everyone out at once. You start to worry that your neighbor is going to withdraw their savings.",
103:"And if they withdraw theirs and everyone else withdraws theirs, the bank's tiny reserve of cash will dry up before I can get my money out.",
104:"Exactly.",
105:"So my most rational defensive move is to sprint to the bank and pull my money out immediately, before the vault is empty.",
106:"And everyone does the exact same rational calculation simultaneously. They rush the doors, the bank runs out of liquid cash, and it collapses.",
107:"We hit the bad equilibrium. The institution is destroyed, and massive amounts of wealth are wiped out.",
108:"And all of it happens just because of a self-fulfilling loss of confidence.",
109:"It's the ten-dollar classroom game played with billions of dollars in people's life savings.",
110:"But I'm curious — is is this dynamic of needing to coordinate with the crowd limited just to finance?",
111:"Not at all. It dictates the architecture and the technology we use every day. Take technology standards, for example.",
112:"Why does the entire corporate world use Microsoft Excel?",
113:"I mean, it's not necessarily because it is the undisputed flawless pinnacle of software engineering.",
114:"Right. There are plenty of competing spreadsheet programs out there.",
115:"But software like that derives its true value from its network of users.",
116:"You need to be able to send a file to a colleague or a client and know they can open it without formatting errors.",
117:"Exactly. The value of the software is intrinsically tied to the network.",
118:"If everyone coordinates on one standard, we achieve the good equilibrium of seamless collaboration.",
119:"But if we all stubbornly choose different incompatible software, just because we think it has slightly better features, we end up in a frustrating uncoordinated bad equilibrium where nothing gets done.",
120:"And the exact same logic applies to dating apps.",
121:"Oh, that makes sense.",
122:"Yeah, the underlying code of a dating app matters very little. The only reason it holds any value is the critical mass of users.",
123:"You could invent an app with the most brilliant matchmaking algorithm in the world. But if you are the only person in your city using it, it is completely useless.",
124:"It's the campus party where nobody shows up.",
125:"You just have to go where the herd goes, even if the user interface is terrible, simply because the coordination itself is the product.",
126:"We even see this behavior in political primaries.",
127:"Voters often face a choice between their idealized candidate and the candidate they think can actually win the general election.",
128:"Right. You don't want your party to fracture and lose.",
129:"So a candidate wins an early primary state, like Iowa or New Hampshire, and suddenly there is this massive bandwagon effect.",
130:"People start voting for that candidate not because their policy preferences changed overnight, but because they are trying to coordinate their vote with the winning team.",
131:"The herd coordinates on that candidate, purely because the momentum signals that everyone else is coordinating on them.",
132:"The fundamental mechanics of game theory just override individual preferences.",
133:"We've established that humans will rationally panic themselves into a corner — tumbling into a bear market, a bank run, or a tech monopoly just because of a loss of collective confidence.",
134:"Yeah.",
135:"The obvious question is: once a market or a classroom plunges into that bad equilibrium, is there a mechanism to pull them out, or are they just doomed?",
136:"Well, in the classroom experiment, they were thoroughly stuck.",
137:"By round three, participation was zero. The psychological freeze was absolute.",
138:"To break it, the professor altered one single variable for round four.",
139:"He allowed a brief moment of communication.",
140:"Here's where it gets really interesting.",
141:"The professor gives the floor to a student named Patrick, who has exactly five seconds to speak to the 250 people who have just watched each other fail repeatedly.",
142:"And Patrick doesn't deliver a grand sweeping emotional monologue.",
143:"He doesn't offer to personally cover anyone's losses.",
144:"He simply stands up and says one incredibly practical sentence.",
145:"Quoting the transcript here, Patrick says: Clearly, if we all invest, we'll all be better off, so everyone should invest.",
146:"That's it.",
147:"They play round four right after he speaks, and almost one hundred percent of the class instantly raise their hands to invest.",
148:"Oh, wow.",
149:"The bear market mentality that had gripped the room was instantly shattered.",
150:"They hit the ninety percent threshold easily.",
151:"Everyone gets their ten dollars back, and everyone unlocks that five dollar profit.",
152:"The real return of coordinated rational decision making is finally achieved.",
153:"But we have to look closely at the mechanics of why this cheap talk actually worked.",
154:"This raises an important question about the nature of information.",
155:"If Patrick had tried that speech in a prisoner's dilemma, it would have failed completely.",
156:"Right.",
157:"Because in a prisoner's dilemma, talk is meaningless.",
158:"You can say let's cooperate all you want, but the mathematical incentive to betray the other person remains dominant.",
159:"Exactly.",
160:"But in a coordination game, we all inherently want to be in the good equilibrium. The incentive is mutual success.",
161:"We just lack the belief that everyone else will act on it.",
162:"So Patrick's intervention worked because he fundamentally shifted the psychological landscape.",
163:"The sources distinguish this as shifting from mutual knowledge to common knowledge.",
164:"Yes, that distinction is crucial.",
165:"Before he spoke, everyone in the room possessed the mutual knowledge that investing together was the best outcome.",
166:"You know it, and the person next to you knew it.",
167:"But I didn't know for sure that the person next to me knew it, and I definitely didn't know if they knew that I knew it.",
168:"Exactly.",
170:"When Patrick stands up and states the obvious out loud to the entire room simultaneously, he creates common knowledge.",
171:"Ah, I see.",
172:"Now, you don't just know that investing is a good idea. You know that everyone else heard Patrick.",
173:"You know that they know that you heard Patrick.",
174:"It creates a self-enforcing agreement.",
175:"Because I watched everyone else hear the same instruction, I instantly update my belief about what the rest of the room is going to do.",
176:"I think: well, surely the rest of the room is going to listen to him.",
177:"Right.",
178:"And because I now believe the rest of the room will invest, it suddenly becomes highly rational for me to invest as well.",
179:"The underlying math of the game didn't change a single digit between round three and round four. The payout was the same, the risk was the same.",
180:"The only thing that changed was the psychological confidence of the herd, engineered by a single clear communicator acting as a focal point.",
181:"Leadership acts as the spark. It aligns expectations and catalyzes the collective belief back toward a bull market.",
182:"Being rational in a vacuum simply isn't enough when you are dealing with group dynamics.",
183:"You have to deeply understand the psychological environment you are operating in.",
184:"You have to account for the beliefs of the herd.",
185:"AbsolutelySo.",
186:"So for you listening right now.",
187:"The next time you are evaluating a shifting market trend, watching a panic unfold in your industry, or even just trying to get a complicated workplace project off the ground,",
188:"ask yourself: are you in a coordination game?",
189:"That's the key question.",
190:"Are people holding back not because the idea is bad, but because they are waiting for a signal that everyone else is on board?",
191:"And if you are in a coordination game, who is doing the communicating?",
192:"Who is establishing that self-enforcing agreement?",
193:"This leaves us with a final thought to ponder on your own.",
194:"We saw how one voice in a lecture hall can coordinate a good outcome, establishing common knowledge and pulling everyone back from the brink.",
195:"Right.",
196:"But we are increasingly living in a world of decentralized finance, anonymous crypto markets, and algorithmic high-frequency trading.",
197:"Yeah, totally different landscape.",
198:"In these massive distributed networks, there is no single leader.",
199:"There is no one who can stand up and give a five-second speech to the global network to instantly restore confidence.",
200:"So how does a decentralized global herd ever find its way back to the good equilibrium, when the market starts to panic without a focal point to guide them?",
201:"That really makes you rethink what stability actually means.",
202:"We want investing to be clean lines and binary facts, but as long as human belief is the engine driving the machine, the waters will always be complex.",
203:"Until next time, keep diving deep.",
}

def main():
    blocks = SRT.read_text(encoding="utf-8").strip().split("\n\n")
    out = []
    miss = []
    for i, b in enumerate(blocks, 1):
        lines = b.split("\n")
        en_text = EN.get(i)
        if en_text is None:
            miss.append((i, lines[2]))
            en_text = lines[2]
        out.append(f"{lines[0]}\n{lines[1]}\n{en_text}")
    OUT.write_text("\n\n".join(out), encoding="utf-8")
    print(f"完成: {len(out)} 段 → {OUT}")
    if miss:
        print(f"⚠ 未翻译 {len(miss)} 条:")
        for i, t in miss:
            print(f"  {i}: {t}")

if __name__ == "__main__":
    main()