#!/usr/bin/env python3
"""翻译 Yale EP2 字幕为英文（分块，含完整翻译表）"""
import sys
from pathlib import Path
try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

SRT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第二期/audio/subtitles.srt")
OUT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第二期/audio/subtitles_en.srt")

# 翻译表：行号 → 英文（1-indexed，对应中文 SRT 的每个字幕块）
EN = {
1:"Have you ever thought, if you could predict the future,",
2:"use very precise logic to predict your competitors,",
3:"or your colleagues, even politicians' next moves,",
4:"what would that be like.",
5:"Wow, that sounds a bit like mind-reading in sci-fi movies.",
6:"Right, that's what I thought at first too.",
7:"Imagine, you no longer rely on intuition to guess,",
8:"nor do you need to read micro-expressions,",
9:"but rather, how to say, have a tool that can directly see through the cards of human decision-making.",
10:"Actually, this is definitely not some mysticism.",
11:"Behind it is a very rigorous logic system,",
12:"which is the core we'll discuss in today's deep dive — game theory.",
13:"We recently translated those classic game theory course materials from Yale University,",
14:"and their after-class exercises, and found a huge treasure trove hidden inside.",
15:"Right, a huge treasure trove,",
16:"and our task today is to, for beginners like you,",
17:"peel away the scary-looking hard math course that is game theory.",
18:"Yes,",
19:"much of the human behavior we find incomprehensible.",
20:"You see, like endless price wars, or climate summits that achieve nothing,",
21:"through the lens of game theory, all reveal a cold,",
22:"but extremely precise inevitability.",
23:"It really is inevitability. Don't worry, this isn't that kind of boring theory course",
24:"that requires blackboard calculus.",
25:"Once you peel off the shell, game theory is essentially the ultimate art of thinking from others' perspective.",
26:"Right, putting yourself in others' shoes.",
27:"But, before bringing this theory into your daily life,",
28:"we first need to figure out what a game actually is.",
29:"Taking a casual stroll on the street — that's not a game.",
30:"The course materials especially emphasized three essential indicators.",
31:"Three indicators, all indispensable,",
32:"namely players, strategies, and payoffs.",
33:"Tell us quickly.",
34:"No problem. Players are the ones making decisions. Strategies are the cards in your hand,",
35:"for example, you can choose to cooperate, or betray.",
36:"And the most core one is actually the third — payoffs.",
37:"Right.",
38:"If we just list you a bunch of strategy options without telling you what making these choices",
39:"would bring in benefits or harms.",
40:"Honestly, at most it's just a menu.",
41:"Haha, ordering from a menu, right.",
42:"Only when your choices can actually affect how much money you ultimately get,",
43:"or how many votes you obtain, or even how many hours of sleep you get.",
44:"then payoffs become the underlying logic driving all behavior.",
45:"So, if we point the magnifying glass at these two words, payoffs,",
46:"many headache-inducing real-world problems suddenly make sense.",
47:"Take the most classic prisoner's dilemma, for example.",
48:"Everyone knows that if both sides cooperate, both win.",
49:"But in reality, people always unhesitatingly walk hand in hand toward double loss.",
50:"It really is like that. For example, companies are now frantically fighting price wars.",
51:"Two companies slash prices desperately to grab market share,",
52:"and in the end, the entire industry's profits are wiped out.",
53:"As a consumer, you might feel great,",
54:"but for companies, this is a complete disaster.",
55:"Absolutely a disaster. And the carbon emission problem is the same.",
56:"Right, every country knows that continuing to pollute will destroy the earth,",
57:"but why can't they stop?",
58:"Because from the perspective of each individual country,",
59:"its payoff structure determines that",
60:"the free-rider strategy is the most rational choice.",
61:"How does one free-ride?",
62:"Think about it. If other countries all put great effort into reducing emissions and the climate improves,",
63:"then I can enjoy good weather without doing anything,",
64:"while not affecting my industrial development.",
65:"Simply winning big.",
66:"Right. Conversely, if other countries don't reduce emissions,",
67:"then even if I grit my teeth and reduce, not only can I not save the earth,",
68:"I'll also cause my own domestic economy to collapse.",
69:"So, no matter what others do,",
70:"continuing to emit is the highest payoff for me.",
71:"Wow, hearing this, I instantly remember the nightmare I hated most in college,",
72:"group projects.",
73:"Great, this example is so classic, it perfectly recreates the prisoner's dilemma.",
74:"Right? At first everyone sat around in the library,",
75:"swearing solemnly, brothers, this time we absolutely won't slack off,",
76:"everyone goes home and does proper research to get an A.",
77:"And then?",
78:"And then the night before the final submission,",
79:"you open the shared document,",
80:"and it's all a pile of copy-pasted garbage.",
81:"I just wonder, since everyone sat together and said everything openly,",
82:"and we all know that getting an A benefits everyone,",
83:"why does this heartfelt communication",
84:"have absolutely no effect?",
85:"Because language communication itself didn't change your payoffs at all.",
86:"Hey, that hits hard.",
87:"No matter how many solemn vows you made in the library,",
88:"as long as the pleasure of lying on the sofa playing games at home",
89:"is still greater than the sense of achievement from painfully reading papers,",
90:"then those promises are just a piece of scrap paper.",
91:"Indeed, scrap paper.",
92:"It's the same at climate summits,",
93:"politicians can talk until the cows come home,",
94:"but as long as the individual payoff of driving a gas-guzzling car at home is still higher than environmental protection,",
95:"high emissions will definitely continue.",
96:"In other words, as long as the incentive structure doesn't change,",
97:"pure talk has no binding power at all.",
98:"To break this lose-lose situation,",
99:"we can't rely on moral appeals,",
100:"but rather on contracts, international treaties, or rules that deduct credit points.",
101:"Right, actually raising the cost of slacking off to change the entire payoff matrix.",
102:"This logic is very clear.",
103:"So, since payoffs and incentive structures determine how opponents will act,",
104:"we can actually reverse-engineer this to predict their next moves, right?",
105:"That's exactly the logic.",
106:"This brings us to the first law of game theory:",
107:"rational people never choose dominated strategies.",
108:"Dominated strategies?",
109:"Right, to make it more intuitive,",
110:"we can use a historical case from the Yale course materials to reason it out.",
111:"Let's say it's the third century BC,",
112:"the Carthaginian general Hannibal is preparing to invade Rome.",
113:"Oh, I know this. Hannibal has two routes to choose,",
114:"one is the flat, easy coastal route,",
115:"the other is the extremely dangerous Alps mountain range.",
116:"Yes. And for the defending side, Rome,",
117:"with limited troops, can only heavily defend one of the two.",
118:"So if we stand in the Roman general's shoes and think with game theory,",
119:"if Hannibal takes the coast route,",
120:"as long as Rome doesn't defend it,",
121:"he can march his army through completely unharmed.",
122:"But if he takes the Alps?",
123:"Whether Rome defends it or not,",
124:"he would have to, due to severe cold and avalanches,",
125:"first lose a third of his troops.",
126:"We call this putting yourself in the other's shoes.",
127:"The Romans, standing in Hannibal's position, calculated the accounts.",
128:"Taking the coast, the worst outcome is a head-on clash with the Roman legions,",
129:"the best outcome is passing through smoothly.",
130:"Taking the Alps, no matter what, would first suffer serious non-combat attrition.",
131:"Right, so in the game theory data,",
132:"taking the Alps is a weakly dominated strategy for Hannibal.",
133:"Because in the vast majority of cases,",
134:"his payoff would be worse than taking the coast,",
135:"or at best equal, but absolutely never better.",
136:"So, based on the assumption that rational people never choose dominated strategies,",
137:"Rome reached the only conclusion:",
138:"Hannibal would definitely take the coast route.",
139:"So they deployed their heavy troops there.",
140:"The logic is perfectly sound, but the script of history wasn't written that way at all.",
141:"Right, Hannibal just refused to play by the rules.",
142:"He really led his army across the deadly Alps,",
143:"and caught Rome completely off guard.",
144:"What does this show?",
145:"It shows that in reality, opponents,",
146:"sometimes deliberately use your rational calculation to set a reverse trap.",
147:"This is precisely the most fascinating part of game theory in real-world application.",
148:"To explore this gap between theory and reality,",
149:"the Yale classroom often plays a game,",
150:"called 'guess two-thirds of the average'.",
151:"How do you play this game?",
152:"The rules are simple.",
153:"Now the whole class picks any integer between one and one hundred and writes it down.",
154:"Whoever picks the number closest to",
155:"two-thirds of the average of all the class's numbers,",
156:"wins the five dollars.",
157:"Wait, let's break down this logic.",
158:"Let's use the same method of eliminating dominated strategies we used before to reason it out.",
159:"Okay, you try.",
160:"First, suppose the whole class has gone crazy,",
161:"everyone picks the largest number, one hundred.",
162:"Then the class average is one hundred,",
163:"two-thirds of it is sixty-six point six,",
164:"which rounds to about sixty-seven.",
165:"Right.",
166:"Numbers above that, like eighty or ninety,",
167:"are meaningless in this game.",
168:"They directly become dominated strategies.",
169:"So as a rational player,",
170:"you would erase all numbers greater than sixty-seven",
171:"from your mind.",
172:"But that's the first level.",
173:"There's a second level.",
174:"Since numbers above sixty-seven are dominated strategies,",
175:"then every rational student won't choose them.",
176:"What does this mean?",
177:"It means wait...",
178:"it means the maximum number the class can choose is only sixty-seven.",
179:"So the new average can at most be sixty-seven.",
180:"And two-thirds of sixty-seven is about forty-five.",
181:"Right, so numbers between forty-six and sixty-seven",
182:"have now also become impossible-to-win dominated strategies,",
183:"all eliminated.",
184:"Wow, this elimination is like Russian dolls nesting inside each other.",
185:"Since everyone won't choose numbers above forty-five,",
186:"then the new target number becomes thirty.",
187:"Since no one will choose thirty, the target becomes twenty.",
188:"If you keep reasoning infinitely with this logic,",
189:"layer by layer, like peeling an onion,",
190:"finally the whole class is left with only one logically perfect number.",
191:"Yes, that number is one.",
192:"Only when everyone picks one,",
193:"two-thirds of one is approximately one,",
194:"can this infinite loop stop.",
195:"But there's a huge bug here.",
196:"What bug?",
197:"If we play this game in real life,",
198:"I absolutely would not pick one.",
199:"Because if there's just one person in the class who didn't wake up,",
200:"or someone deliberately messing around who casually picks one hundred,",
201:"the average gets instantly pulled up.",
202:"The person who picked one would lose badly.",
203:"Right, people aren't emotionless random number generators.",
204:"Your intuition is very sharp.",
205:"Actually, the real result when they played this game in the Yale classroom back then was,",
206:"the class average was about thirteen,",
207:"and the eventual winner picked the number nine.",
208:"It never fell to the theoretical middle point of one.",
209:"Not at all.",
210:"There's a decisive factor hidden here,",
211:"which in game theory is called common knowledge.",
212:"Common knowledge, it sounds like saying common sense that everyone knows.",
213:"It's not just common sense.",
214:"In the game we just played, to dare to pick one,",
215:"the premise is not only that you yourself must be perfectly rational,",
216:"you also have to believe that all your classmates are rational.",
217:"That's already hard enough.",
218:"Not only that,",
219:"you also have to believe that all your classmates believe that you believe they are rational,",
220:"and so on,",
221:"this chain of trust must extend infinitely.",
222:"Oh my god, this sounds so convoluted.",
223:"To explain how hard it is to achieve this common knowledge in reality,",
224:"scholars proposed a thought experiment with pink hats.",
225:"Let's talk about it.",
226:"Suppose two people stand on stage,",
227:"put a hat on each of them,",
228:"and tell them,",
229:"at least one of you is wearing a pink hat.",
230:"Okay, at least one pink hat.",
231:"Then they open their eyes and look at each other.",
232:"Both can clearly see that the other's hat is pink.",
233:"At this point, that the other person is wearing a pink hat — for each of them,",
234:"is it known?",
235:"Of course it's known.",
236:"I see your hat,",
237:"but I don't know whether you saw my hat.",
238:"If my hat is white,",
239:"that means you could only see a white hat.",
240:"Right, I know the facts,",
241:"and I know that you know the facts,",
242:"but I can't be certain",
243:"whether you know that I know.",
244:"Once this nested knowledge structure breaks,",
245:"the logical chain of iteratively eliminating strategies also breaks.",
246:"So in reality,",
247:"when you can't assume everyone will, like computers,",
248:"reason infinitely,",
249:"this tool fails.",
250:"Yes, we have to put it away,",
251:"and switch to a more powerful, more practical concept:",
252:"best response.",
253:"Best response.",
254:"This term sounds very straightforward.",
255:"Does it mean, based on others' decisions,",
256:"I find a response that's most beneficial to me.",
257:"That's exactly what it means.",
258:"The core of best response is that",
259:"you no longer need to guess whether",
260:"others are infinitely rational.",
261:"Then what do I need to do?",
262:"You just need to form an expectation about",
263:"what others might do,",
264:"and then, based on that expectation,",
265:"choose the action that brings you the maximum payoff.",
266:"We can use a very famous theorem in political science, the median voter theorem,",
267:"to see how it works.",
268:"Political science, that's quite a crossover!",
269:"Actually, the underlying logic is the same.",
270:"Suppose there's a political spectrum from one to ten,",
271:"one represents the far left,",
272:"ten represents the far right,",
273:"voters are evenly distributed across these ten notches.",
274:"Now two politicians are running in the election.",
275:"The rule is,",
276:"voters will definitely vote for",
277:"the candidate whose position is closest to their own.",
278:"So if I pick one,",
279:"the most extreme left wing,",
280:"and my opponent picks two,",
281:"then my opponent will take all the voters from notch three to ten,",
282:"because they're all closer to him.",
283:"Right, you only get those pitiful votes at notch one.",
284:"So I immediately understand that",
285:"the extremes, one and ten, absolutely cannot be chosen.",
286:"Since the extreme positions can't be chosen,",
287:"the two politicians will start making best responses to each other's positions.",
288:"You pick two, I pick three to squeeze you.",
289:"You see I picked three,",
290:"you'll pick four to surround me.",
291:"In this game of fighting for votes,",
292:"their positions will ultimately, like magnets,",
293:"keep converging toward the center,",
294:"and finally both squeeze together at positions five and six,",
295:"desperately fighting for this group of swing voters.",
296:"Wow, this explains so much in history.",
297:"Many campaign strategies,",
298:"like Kennedy and Nixon, or Clinton, at the critical stage of elections,",
299:"they often blur out their camp's most radical slogans.",
300:"Yes, and instead use moderate policies to court the middle.",
301:"We're just objectively using these cases to explain the model,",
302:"with no political bias.",
303:"Of course, we're just discussing game theory.",
304:"This logic is truly pervasive.",
305:"Not only does it explain politics,",
306:"it also explains why on the same commercial street,",
307:"two competing gas stations or cafes",
308:"never open evenly at the two ends of the street.",
309:"But insist on being huddled right together, opening at the very center of the street.",
310:"Everyone is squeezing each other's living space toward the middle.",
311:"It's truly amazing.",
312:"But speaking of best response,",
313:"that data about penalty shootouts in the materials,",
314:"is what really makes you gasp.",
315:"Penalty shootouts are considered by many economists to be the most perfect laboratory for studying game theory in the real world.",
316:"Why do you say that?",
317:"For the striker, there are three shooting directions: left, center, right.",
318:"For the goalkeeper,",
319:"the diving directions are generally left and right, two of them.",
320:"The course showed a set of real statistics for high-level professional players.",
321:"What does the data say?",
322:"If the striker shoots to the left,",
323:"and the goalkeeper also happens to dive left,",
324:"because the goalkeeper guessed right,",
325:"the scoring rate is only about 40%.",
326:"But if the goalkeeper dives the wrong way,",
327:"to the right,",
328:"the scoring rate soars to over 90%.",
329:"The right side data is basically similar, right?",
330:"Now here's the key point.",
331:"If in this life-or-death moment,",
332:"the striker goes against the grain,",
333:"and directly kicks the ball to the very center of the goal?",
334:"The data is very cold.",
335:"Given this set of professional players' data,",
336:"whether the goalkeeper dives left or right,",
337:"as long as the striker kicks the ball down the middle,",
338:"the scoring rate is always stable at around 60%.",
339:"Guessing 60%?",
340:"Yes.",
341:"If you draw a chart in your mind,",
342:"this line representing the win rate of shooting center,",
343:"is always pressed below the left and right lines.",
344:"This means,",
345:"no matter how you and the goalkeeper act,",
346:"shooting center can never bring the highest expected payoff.",
347:"So the conclusion is that in professional-level penalty shootouts,",
348:"kicking the ball to the center is absolutely not a best response.",
349:"Right, absolutely don't kick the ball to the center.",
350:"But wait,",
351:"what if I don't play by the rules?",
352:"What do you mean?",
353:"What if I'm not one of those professional stars who shoot precisely wherever they aim,",
354:"I'm just an amateur with particularly bad skills,",
355:"who only knows 'power creates miracles'.",
356:"Good, power creates miracles.",
357:"Right, if I insist on aiming for the left or right corner of the goal,",
358:"there's a high probability that my own footwork is bad,",
359:"and I'd directly kick the ball into the stands,",
360:"with a scoring rate that might not even reach 20%.",
361:"Instead, if I close my eyes and blast the ball with all my strength toward the very center of the goal,",
362:"at least I can guarantee the ball stays within the goal frame.",
363:"At this point,",
364:"isn't kicking the center the best choice?",
365:"The point you raise is simply brilliant.",
366:"This is precisely the most critical step in economic modeling.",
367:"The thinking you just showed vividly demonstrates what it means to enrich the model.",
368:"Enrich the model?",
369:"Right, our previous conclusion was built on the variable that",
370:"kicking to the left or right won't result in mistakes.",
371:"Once we add the new variable you mentioned,",
372:"that is, shooting with great power",
373:"but extremely low precision, into the model,",
374:"the base scoring rate of kicking to the sides",
375:"will drop off a cliff because of the risk of kicking wide.",
376:"With that, the chart is different.",
377:"Yes, at this point, the line representing shooting center rises in relative position.",
378:"Not only that,",
379:"because your ball speed is extremely fast,",
380:"even if the goalkeeper stands still without moving,",
381:"he might not be able to react in time.",
382:"I see,",
383:"so in the finely-tuned new model,",
384:"shooting center suddenly becomes a completely reasonable best response.",
385:"Game theory is by no means a rigid dogma;",
386:"it keeps evolving as real-world variables change.",
387:"This makes the discipline come alive.",
388:"Okay, now we know,",
389:"for a single action by the opponent,",
390:"how to find our best response.",
391:"Now, push this logic to its extreme.",
392:"If in the entire game,",
393:"every player is simultaneously making best responses to others' choices,",
394:"what would happen?",
395:"Good question.",
396:"This finally brings us to the ultimate boss of today's deep dive:",
397:"the Nash equilibrium.",
398:"Nash equilibrium,",
399:"this term sounds really lofty and mysterious.",
400:"Sounds intimidating.",
401:"But we can use a very down-to-earth partner game to peel it open.",
402:"Imagine two law partners who founded a law firm together,",
403:"or, as everyone is very familiar with,",
404:"two students staying up late together doing a group assignment.",
405:"Again the nightmare of homework.",
406:"The rule is,",
407:"the final profit or score of the project",
408:"is split 50-50 between the two.",
409:"But all the effort put into this project,",
410:"whether it's researching materials, writing code, or losing hair staying up late,",
411:"this painful cost is borne 100% by each person individually.",
412:"Of course, the two working together also have the so-called synergy effect,",
413:"that is, one plus one is greater than two.",
414:"Right,",
415:"but the most realistic part of this setting is that",
416:"everyone is secretly calculating,",
417:"since the final outcome is split half and half,",
418:"why not do a little less myself,",
419:"and let the other person do a bit more?",
420:"Yeah, this is too real.",
421:"In economics, this is called externality.",
422:"When you're sitting in front of the computer at two in the morning,",
423:"considering whether to spend one more hour",
424:"polishing the report to make it more perfect,",
425:"the mental arithmetic in your head goes like this.",
426:"The exhaustion of staying up this extra hour",
427:"is borne 100% by myself.",
428:"But the extra value created by this hour,",
429:"half of it is given away for free to my partner.",
430:"Because you can't exclusively enjoy all the returns of your extra effort.",
431:"Rational calculation will prompt you to stop your current work,",
432:"and go slack off or sleep.",
433:"So, in this mutual-slacking probing,",
434:"where exactly is the Nash equilibrium hidden?",
435:"Imagine you two are now staring at the same shared document.",
436:"You see your partner hasn't typed for a long time,",
437:"you think he's slacking off,",
438:"so you also slow down your pace.",
439:"This is you making a best response.",
440:"Haha, then when my partner sees me slowing down,",
441:"he definitely doesn't want to lose out.",
442:"Right, so he further reduces his level of effort,",
443:"also his best response.",
444:"You both keep adjusting your bottom lines based on",
445:"each other's level of laziness.",
446:"Until you both fall to a critical point.",
447:"What kind of critical point?",
448:"At this point, the project can barely pass.",
449:"If you do a little less,",
450:"the project completely fails and everyone is doomed.",
451:"But if you do a little more,",
452:"you feel it's too much of a loss.",
453:"In other words, my partner is having exactly the same thought right now.",
454:"In this early morning of staying up to the brink of collapse,",
455:"neither of us is willing to type one more word,",
456:"and neither dares to just shut down the computer and go to sleep.",
457:"It's this moment.",
458:"This intersection where you both make best responses to each other,",
459:"is the Nash equilibrium.",
460:"At this point, something extremely decisive happens.",
461:"What?",
462:"Neither side has any incentive to unilaterally change its strategy.",
463:"Whoever moves first loses.",
464:"This is the most core definition of the Nash equilibrium.",
465:"It's an extremely stable,",
466:"structural stalemate that no one is willing to actively break.",
467:"Wow, this completely overturns my previous understanding.",
468:"I used to think that since it's called an equilibrium,",
469:"it must be some kind of perfect harmony,",
470:"an ideal state where everyone is happy.",
471:"Many beginners think this way.",
472:"But it turns out, the Nash equilibrium doesn't mean the best outcome at all.",
473:"Like the prisoner's dilemma we mentioned at the very beginning,",
474:"where everyone falls into double loss,",
475:"that is also a Nash equilibrium.",
476:"A very thorough insight.",
477:"It merely means that under the current game rules,",
478:"everyone is stuck dead in a quagmire where no one dares to stick their head out.",
479:"This is not heaven.",
480:"This is basically a trap that locks everyone in.",
481:"Great summary. Looking back at our journey,",
482:"from the ineffective talk in the prisoner's dilemma,",
483:"to eliminating dominated strategies in Hannibal's story and the numbers game,",
484:"to the best responses in gas station locations and penalty shootouts.",
485:"Finally, we unveiled the veil of the stalemate inside the Nash equilibrium.",
486:"Right.",
487:"You'll find that game theory is by no means just a theory in an ivory tower.",
488:"It's a pair of X-ray glasses for seeing through human interaction,",
489:"business competition, and everyday decision-making.",
490:"Master it, and the world you see",
491:"is no longer a series of isolated coincidences.",
492:"but countless interlocking gears and calculations.",
493:"Indeed.",
494:"I hope the hardcore logic we've sorted out for you today,",
495:"can become, the next time you face a critical decision,",
496:"even if it's just in the next group assignment,",
497:"when you're strategizing against your partner,",
498:"your most powerful weapon of thought.",
499:"Remember, don't just look at what others say,",
500:"look at the payoffs and incentives they face.",
501:"Right, payoffs are the key.",
502:"Before we end today,",
503:"I want to throw out a thought experiment,",
504:"also from the Yale after-class exercises,",
505:"for you to solve on your own.",
506:"Oh, this sounds quite interesting.",
507:"Yes, in the world of game theory, holding an advantage,",
508:"or rather, power in hand,",
509:"is it really always a good thing?",
510:"Imagine a committee of three people.",
511:"They're voting to select this year's best art award.",
512:"There are three candidate works: A, B, and C.",
513:"Three people voting for three works can easily end in a tie.",
514:"Right, to prevent a 1-1-1 tie deadlock in the voting,",
515:"the rules specially grant committee member A",
516:"an enormous privilege.",
517:"Once there's a tie, the final result will be completely decided",
518:"by that single vote of member A.",
519:"It sounds like member A controls the whole stage.",
520:"On the surface,",
521:"he does have absolute overwhelming power,",
522:"but don't forget, the other two members are no pushovers.",
523:"Precisely because they clearly know that member A",
524:"holds this privilege, and know which work A favors most,",
525:"so to prevent A's favorite work from ultimately winning,",
526:"they will strategically ally in advance.",
527:"Right, through clever tactical voting,",
528:"they directly kill A's favorite option in the very first round.",
529:"This problem has a very thought-provoking name in the course materials:",
530:"'power is exactly your weakness'.",
531:"The absolute advantage granted to you by the rules,",
532:"because it exposes your threat in advance, instead forces others to ally.",
533:"making you the biggest target.",
534:"What about you?",
535:"In real-world workplace or life games,",
536:"what position are you in?",
537:"Those privileges and advantages you take pride in,",
538:"could they be exactly the origin point where others scheme against you?",
539:"Before your next decision,",
540:"why not try to thoroughly stand in someone else's shoes and look,",
541:"see you next time in our deep dive.",
}

def main():
    blocks = SRT.read_text(encoding="utf-8").strip().split("\n\n")
    out = []
    for i, b in enumerate(blocks, 1):
        lines = b.split("\n")
        en_text = EN.get(i)
        if en_text is None:
            print(f"[WARN] 缺翻译: {i}: {lines[2]}")
            en_text = lines[2]
        out.append(f"{lines[0]}\n{lines[1]}\n{en_text}")
    OUT.write_text("\n\n".join(out), encoding="utf-8")
    print(f"完成: {len(out)} 段 → {OUT}")

if __name__ == "__main__":
    main()
