#!/usr/bin/env python3
"""翻译 Yale EP4 中文 SRT 为英文，输出 subtitles_en.srt（保留原时间戳）"""
import sys
from pathlib import Path
try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

SRT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第四期/audio/subtitles_zh.srt")
OUT = Path(r"E:/projects/news-talk/yale大学公开课系列讲谈/第四期/audio/subtitles_en.srt")

# 段号 → 英文（1-indexed，对应 subtitles_zh.srt 的每个字幕块）
EN = {
1:"Have you ever walked into a high school cafeteria, or maybe a massive networking event, and just noticed how people naturally separate into distinct groups?",
2:"Without anyone giving orders or assigning seats, the whole room is completely divided geographically.",
3:"Almost like an invisible magnetic force pulling similar people together and pushing different people apart. You see it everywhere.",
4:"Exactly. And when we see that kind of stark division, the immediate assumption we make is that it must be intentional.",
5:"We assume that if a room or a city is segregated, the people there must inherently want to be segregated. They sit together because they only want to be around people exactly like them.",
6:"But today's deep dive is exploring the hidden incentives behind that kind of group segregation.",
7:"We are looking at a fascinating mathematical framework — Thomas Schelling's Nobel Prize-winning model.",
8:"It completely challenges everything we assume about social behavior.",
9:"Schelling's work is fundamental to game theory. Mathematically, it proves that you cannot infer individual preferences from collective outcomes.",
10:"Our mission today is to unpack the exact mechanism: how a society full of individuals who genuinely desire integration can end up completely segregated.",
11:"To understand this, we need to strip away our real-world assumptions and play a theoretical game.",
12:"Let's play it out.",
13:"Our primary source today is a live simulation of this model that the Yale Game Theory lecture runs with students.",
14:"Imagine two towns: East town and West town.",
15:"Got it. Two towns.",
16:"Each town has a maximum capacity of exactly one hundred thousand people. And in our world, there are only two types of people. Let's call them tall and short.",
17:"Or green shirts and blue shirts — the labels are arbitrary.",
18:"Every single person in this scenario must choose to live in East town or West town. Their choice is driven by a set of utility payoffs.",
19:"Which is game theory speak for a happiness score, right?",
20:"Think of it as a score that measures happiness based entirely on the demographics of the town you live in.",
21:"So how does the scoring work? There are three rules. Rule one: if you move to a town and become an absolute minority, your payoff is zero.",
22:"Zero?",
23:"Yes. Like being the only tall person in a town of ninety-nine thousand nine hundred and ninety-nine short people. You are profoundly unhappy.",
24:"Being the absolute odd one out is super uncomfortable. Extreme isolation just drags your utility to nothing.",
25:"That's the worst-case scenario. Rule two: if you live in a town where your group is the one hundred percent majority — only your own kind — your payoff is zero point five.",
26:"So it's fine, but far from the maximum score.",
27:"Right. It's just okay. Being completely surrounded by only your own group is basically mediocre. Half a point out of one.",
28:"And rule three?",
29:"Rule three is the clincher. If you live in a perfectly mixed town — an exact fifty-fifty split of tall and short — your payoff is one. Absolute peak happiness.",
30:"Like walking into a massive party that's a beautifully diverse mix of all different social circles. That's the most fun.",
31:"But if you walk into a party and it's literally just your immediate co-workers, it's comfortable but maybe a bit monotonous.",
32:"That's your zero point five. But if you walk into a room full of five hundred strangers and you are the solitary person from your friend group, that's incredibly awkward. You just want to leave immediately. Payoff of zero.",
33:"That analogy perfectly captures the human element of the math.",
34:"Now let's pull back and look at the core assumption of this model: every single person actively prefers integration.",
35:"All two hundred thousand of them?",
36:"Yes. Their ideal state, their absolute highest utility, is a perfectly diverse fifty-fifty society.",
37:"Which means literally nobody wants segregation.",
38:"Nobody.",
39:"So if everyone wants a fifty-fifty split, logic suggests the towns would naturally form into two perfectly integrated fifty-fifty communities, right?",
40:"That is the totally logical assumption. But when the Yale professor ran this game live, the outcome was entirely different.",
41:"What happened?",
42:"He set the room up in a striking pattern, row by row, perfectly alternating tall and short students. He forced them into that utopian fifty-fifty integrated state, where everyone was getting their maximum payoff of one.",
43:"They were given the perfect society right out of the gate.",
44:"You'd think so. But then he told the students to close their eyes, think about their individual payoffs, and simultaneously choose which town they actually wanted to live in.",
45:"And then?",
46:"Almost immediately, the integration unraveled. In just a couple of rounds, the room heavily segregated. The vast majority of short students clustered into East town, and tall students fled to West town.",
47:"I am really struggling with the logic here. Every single student knew they would be happiest in a mixed town.",
48:"I know, it's wild. Yet they all abandoned it for segregated towns where they willingly settled for a zero point five payoff.",
49:"Why would rational people sabotage their own ideal outcome like that?",
50:"To understand that, we have to look at the mechanics of what game theorists call a Nash equilibrium.",
51:"Nash equilibrium?",
52:"A Nash equilibrium is a state where no individual player has anything to gain by changing their own strategy, assuming everyone else's strategy stays the same.",
53:"And the perfect fifty-fifty split actually is a Nash equilibrium. If the town is exactly fifty-fifty, nobody wants to leave, because everyone is enjoying their maximum happiness of one.",
54:"So if it's an equilibrium, why did it fall apart?",
55:"Because game theory categorizes this specific state as a very weak and unstable equilibrium.",
56:"Is it like trying to balance a pencil perfectly on its tip? It works in theory, but the environment around it has to be impossibly still.",
57:"That is the exact mechanism. It requires absolute flawless precision. If a slight breeze blows, gravity takes over and it falls.",
58:"So in our town scenario, what's the breeze?",
59:"The breeze is just random human movement. Say we are in that fifty-fifty utopian East town, but by pure chance a new apartment complex finishes construction, and five percent more short people happen to move in.",
60:"The ratio shifts. It's not fifty-fifty anymore. It's maybe fifty-five to forty-five.",
61:"If you are one of the tall people in East town, you notice you are starting to become a minority. And as your proportion drops, your payoff starts slipping from that perfect one down toward that terrifying zero.",
62:"You start feeling that awkwardness of being the odd one out at the party. You start to panic.",
63:"So your rational response is to move to West town, where you know there are more tall people.",
64:"But when you leave East town, you take another tall person out of the equation. The ratio in East town just got even worse for the tall people who stayed behind.",
65:"Now it's sixty-forty. Which terrifies the remaining tall people even more. So they leave, which pushes the ratio to seventy-thirty, then eighty-twenty.",
66:"It's a massive domino effect. Or, as Schelling called it, a tipping point.",
67:"A tipping point. A tiny random deviation triggers an unstoppable cascade.",
68:"And the individuals aren't moving because they hate the other group. They aren't moving because they want to live in a one hundred percent segregated town.",
69:"They are moving purely to avoid being caught in the extreme minority.",
70:"They are running away from the zero. They aren't running toward the zero point five.",
71:"But the collective result of everyone trying to avoid the zero is that the whole system crashes into total segregation.",
72:"Let's think about the math of what happens after the crash. Once they hit total segregation, are they just stuck?",
73:"Completely stuck. Because unlike the fifty-fifty split, total segregation is a strict or strong equilibrium.",
74:"If East town becomes one hundred percent short people, and I am a short person with my mediocre zero point five payoff, if I decide to be the brave pioneer and move to West town to try to reintegrate it, I arrive in West town as the absolute minority of one. My payoff instantly plummets to zero.",
75:"You get severely punished by the math for trying to do the right thing.",
76:"There is zero individual incentive to be the first person to cross the line.",
77:"That is so depressing.",
78:"It is. Even though they all genuinely prefer the fifty-fifty world, they are mathematically trapped in the one hundred percent segregated world.",
79:"Taking this mathematical model and applying it to the real world is where this gets incredibly heavy. We are talking about a fundamental divergence between what individuals desire and what society actually produces.",
80:"It really exposes a mass of sociological illusion.",
81:"When anthropologists or sociologists study human societies across history and continents, they observe segregation practically everywhere.",
82:"And it is entirely intuitive to look at a deeply segregated society and just conclude: human beings must inherently prefer this. They are choosing this because it reflects their inner desires.",
83:"You see a cafeteria divided, you assume it's by choice and preference. You assume the macro picture is just a large-scale painting of the micromotives.",
84:"But Schelling's model mathematically proves that inference is fundamentally flawed. You cannot look at a macro-level collective outcome and automatically assume it reflects micro-level individual preferences.",
85:"A society entirely composed of people who genuinely desire diversity can still end up strictly segregated.",
86:"Exactly.",
87:"The source material grounds this in a stark reality: in Connecticut, actually.",
88:"The Yale example, right?",
89:"Yes. The city of New Haven, where Yale is located, is a relatively integrated urban area with a really wide array of ethnicities. But if you drive just twenty miles north into rural Connecticut to the Durham Fair, which is a massive, super-popular agricultural event, the demographics change shockingly.",
90:"The crowd at this public event, just a twenty-minute drive away, is overwhelmingly, strikingly white.",
91:"I have to pause here and push back on the implications a bit. Hearing a model like this, someone could easily say: well, this means systemic prejudice isn't real, it's just a game theory tipping point.",
92:"Doesn't this mathematical framework kind of let people off the hook for actual racism or exclusionary behavior?",
93:"It's a completely valid point. And to be crystal clear, the models we are looking at today are not making a political statement or claiming that actual prejudice doesn't exist. People obviously do hold strong, active prejudices.",
94:"Absolutely, they do.",
95:"What the model proves is something arguably more unsettling. You don't actually need active malice to create a divided world. You only need a population of people who have a slight, perhaps even subconscious aversion to being the extreme minority.",
96:"If everyone just wants to make sure they aren't the solitary odd one out in the room, the mathematics of the tipping point will do the rest.",
97:"The fear of the zero.",
98:"Yes. The fear of the zero drives the society into district segregation, even if nobody actually holds any ill will toward the other group.",
99:"That is a really profound realization. Because it means even if a society manages to completely cure itself of active prejudice, as long as we hold on to that perfectly human instinct to avoid being isolated, we still end up divided.",
100:"That's the scary part of the math.",
101:"So if individual freedom of choice inevitably leads to a cascade that traps us in an outcome nobody actually wants, how do we fix the system? Are we just doomed to be stuck in these segregated zero point five towns forever?",
102:"This is where the game theory takes a totally fascinating turn. Hidden inside this model is a third, very unconventional equilibrium.",
103:"A secret third option?",
104:"We know that if people choose based on their individual comfort, the system tips into segregation. But what if every single person in the game — all one hundred thousand tall and one hundred thousand short — simultaneously decided to completely abandon West town and all try to move into East town?",
105:"But East town only has a capacity of one hundred thousand. There are two hundred thousand people. Half of them literally wouldn't fit.",
106:"Exactly. The local government of East town would be facing a massive housing crisis. They would have to turn one hundred thousand people away.",
107:"So how do they decide who gets to stay?",
108:"To resolve the crisis fairly, the government would have to allocate the surplus randomly. They would essentially pull names out of a giant hat, randomly assigning half the population to stay in East town and forcing the other half into West town.",
109:"So the government just randomizes everyone.",
110:"According to the law of large numbers, if you take a massive population of tall and short people and randomly assign them to two buckets, you will almost perfectly achieve a fifty-fifty split in both towns.",
111:"You instantly return everyone to their maximum payoff of one. Everyone achieves their ideal peak happiness.",
112:"But the only way they got there was by completely abdicating their individual right to choose where they live.",
113:"That is such a strange paradox. By completely giving up our right to choose and letting a central authority randomly place us, we actually end up mathematically happier and better off.",
114:"It completely flips our understanding of free choice on its head.",
115:"And it translates directly into some of the most complex social policies in modern history. The mathematical quirk of this randomized equilibrium actually mirrors the policy of school busing in the United States during the nineteen-sixties and seventies.",
116:"Busing was incredibly contentious. The friction of implementing it was massive, because geographic housing choices had led to highly segregated neighborhoods, and local schools were highly segregated as a direct result.",
117:"To forcefully integrate the schools, the government overrode local geographic choices. They randomly assigned students to schools and bused them across town.",
118:"Keeping the political and social debates aside, from a pure game theory perspective, busing is essentially the real-world application of that third randomized equilibrium.",
119:"You override the individual choice mechanism because it inevitably causes the tipping point. You have to change the rules of the game entirely.",
120:"Let's look at a slightly less politically charged example. You can actually see this exact mathematical crisis play out historically at Harvard University.",
121:"Up until the nineteen-nineties, Harvard allowed its undergraduate students to freely choose which residential house they wanted to live in. The administration thought they were doing a good thing by giving students autonomy.",
122:"Let me guess. Giving eighteen-year-olds the freedom to choose where they live triggered the Schelling tipping point and the houses segregated.",
123:"Severe, entirely predictable segregation. Kirkland House, for instance, became known as the Jock House. Because athletes wanted to live near other athletes, they grouped together. And because a huge proportion of the hockey team was from Canada, Kirkland House essentially became the Canadian House.",
124:"But also terrible for diversity. Other houses became starkly segregated by wealth or by specific academic backgrounds.",
125:"The administration realized pretty quickly that giving students the freedom to choose was actually destroying the diverse cross-pollinated college experience they were supposed to provide. So the macro outcome was totally failing the micro intent.",
126:"If choice caused the tipping point, the administration had to pull the plug on giving students a choice at all.",
127:"They adopted the policy that their rival, Yale, had been using all along: central randomization. Harvard took away the student's ability to choose their house and started assigning them completely at random.",
128:"They literally applied the third equilibrium. They forced the randomization to save the system.",
129:"It highlights a crucial lesson for anyone trying to design a system: whether you are an urban planner, a sociologist, or a tech CEO, seemingly irrelevant details in how a system is structured can completely alter the macro outcome.",
130:"Sometimes, the only way to beat a broken system is to recognize that individual optimization is actively causing a collective failure. You have to insert a mechanism that bypasses individual choice to protect the collective good.",
131:"We've covered a lot of profound ground today.",
132:"Indeed. But the key takeaway here is incredibly counterintuitive: collective outcomes do not always reflect individual desires. A strictly segregated society does not necessarily mean you have a society of people who desire segregation.",
133:"We have to look past the surface of the macro outcome and interrogate the micro-incentives.",
134:"That is really the true genius of Thomas Schelling's framework. It really makes you evaluate the world around you differently.",
135:"Before we wrap up, I want to leave you with a final thought to mull over on your own.",
136:"Think about your own digital life. Every day, we hear complaints about the internet being segregated into these toxic, polarized echo chambers.",
137:"We blame the algorithms, we blame political tribalism. But based on Schelling's model, what if the algorithms aren't just feeding us what we want?",
138:"What if deep down we all actually want a diverse, balanced feed of opinions, but our slight, perfectly human discomfort at being the only one with a certain viewpoint in a comment section mathematically drives us to flee?",
139:"Are we constantly running away from the digital zero, retreating into our digital east towns and west towns, segregating ourselves online without even knowing it? Are we trapped in a digital tipping point?",
140:"That is a terrifying but completely necessary question to consider.",
141:"Something to think about the next time you walk into a crowded room or log onto a crowded timeline.",
    142:"A strictly segregated society does not necessarily mean a society of people who desire segregation. We have to look past the surface of the macro outcome and interrogate the micro-incentives.",
    143:"That is really the true genius of Thomas Schelling's framework. It really makes you evaluate the world around you differently.",
    144:"Before we wrap up, I want to leave you with a final thought to mull over on your own. Think about your own digital life.",
    145:"Every day, we hear complaints about the internet being segregated into these toxic, polarized echo chambers.",
    146:"We blame the algorithms, we blame political tribalism. But based on Schelling's model, what if the algorithms aren't just feeding us what we want?",
    147:"What if deep down we all actually want a diverse, balanced feed of opinions?",
    148:"But our slight, perfectly human discomfort at being the only one with a certain viewpoint in a comment section mathematically drives us to flee.",
    149:"Are we constantly running away from the digital zero, retreating into our digital east towns and west towns, segregating ourselves online without even knowing it?",
    150:"Are we trapped in a digital tipping point?",
    151:"That is a terrifying but completely necessary question to consider.",
    152:"Something to think about the next time you walk into a crowded room or log onto a crowded timeline.",
    153:"You see, from the cafeteria to the city, from schools to the internet, Schelling's tipping point is everywhere.",
    154:"It tells us that a tiny deviation in micro-level individual optimization can snowball into a macro outcome nobody wants.",
    155:"And the key to fixing it is often having the courage to change the rules themselves.",
    156:"Whether through random allocation or building common knowledge, it takes someone to step up and break the deadlock that nobody wants to move on first.",
    157:"Perhaps this is today's deepest lesson: individual freedom and individual rationality themselves can be part of the collective trap.",
    158:"Read the incentives, and you can design a better world.",
    159:"We started with a classroom game and saw the underlying logic of how society runs.",
    160:"So what does this mean for you and me, ordinary people?",
    161:"First, when you see any segregation, do not rush to blame human nature. Second, if you want to drive change, calling for it is not enough — you have to change the rules of the system.",
    162:"Third, beware of your own small group: the zero point five of the comfort zone is often the beginning of a collective trap.",
    163:"And fourth, always remember Schelling's elegant proof: you cannot infer individual intent from a collective outcome.",
    164:"Okay, that's a lot to digest.",
    165:"Let's recap today's thread: three rules of happiness, the fifty-fifty utopia, the weak equilibrium that collapses at the slightest breeze.",
    166:"Then the dominoes of the tipping point, trapping everyone in the strong equilibrium of segregation.",
    167:"And then the third equilibrium: giving up choice through random allocation actually delivers everyone's peak happiness.",
    168:"Finally, the real world: school busing, Harvard houses, digital echo chambers.",
    169:"The whole thread is really about the same thing: how rational micro-level choices turn into macro-level collective traps.",
    170:"And the way out is often hidden in changing the rules themselves.",
    171:"Thanks for joining us on this deep dive. Until next time, keep diving deep.",
}
def main():
    blocks = SRT.read_text(encoding="utf-8").strip().split("\n\n")
    out = []
    miss = []
    for i, b in enumerate(blocks, 1):
        lines = b.split("\n")
        en_text = EN.get(i)
        if en_text is None:
            miss.append((i, lines[2]))
            en_text = lines[2]
        out.append(f"{lines[0]}\n{lines[1]}\n{en_text}")
    OUT.write_text("\n\n".join(out), encoding="utf-8")
    print(f"完成: {len(out)} 段 → {OUT}")
    if miss:
        print(f"⚠ 未翻译 {len(miss)} 条:")
        for i, t in miss:
            print(f"  {i}: {t}")

if __name__ == "__main__":
    main()